name: Update Screenshot

on:
  push:
    branches:
      - main

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run screenshot script
        run: node take-screenshot.js

      - name: Commit and push screenshot
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add screenshot.png
          git commit -m "Update screenshot [skip ci]"
          git push
